// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MilitaryComparator.Data;

#nullable disable

namespace MilitaryComparator.Migrations
{
    [DbContext(typeof(MilitaryDbContext))]
    partial class MilitaryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("MilitaryComparator.Models.Entities.ArmoredVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Armor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EnginePower")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Length")
                        .HasColumnType("REAL");

                    b.Property<string>("MainArmament")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxSpeedOffRoad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxSpeedRoad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Range")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecondaryArmament")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Suspension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalProduced")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("NationId");

                    b.ToTable("ArmoredVehicles");
                });

            modelBuilder.Entity("MilitaryComparator.Models.Entities.CrewMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArmoredVehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArmoredVehicleId");

                    b.ToTable("CrewMembers");
                });

            modelBuilder.Entity("MilitaryComparator.Models.Entities.Nation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlagImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Nations");
                });

            modelBuilder.Entity("MilitaryComparator.Models.Entities.ArmoredVehicle", b =>
                {
                    b.HasOne("MilitaryComparator.Models.Entities.Nation", "Nation")
                        .WithMany("Vehicles")
                        .HasForeignKey("NationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nation");
                });

            modelBuilder.Entity("MilitaryComparator.Models.Entities.CrewMember", b =>
                {
                    b.HasOne("MilitaryComparator.Models.Entities.ArmoredVehicle", "ArmoredVehicle")
                        .WithMany("Crew")
                        .HasForeignKey("ArmoredVehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArmoredVehicle");
                });

            modelBuilder.Entity("MilitaryComparator.Models.Entities.ArmoredVehicle", b =>
                {
                    b.Navigation("Crew");
                });

            modelBuilder.Entity("MilitaryComparator.Models.Entities.Nation", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
